version: "3.9"

services:
  # ------------------ MONGODB SERVICES ------------------

  mongo:
    image: mongo:7
    container_name: training-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  # auth-mongo:
  #   image: mongo:7
  #   container_name: auth-mongo
  #   restart: unless-stopped
  #   volumes:
  #     - auth_mongo_data:/data/db
  #   networks:
  #     - training-network

  # user-mongo:
  #   image: mongo:7
  #   container_name: user-mongo
  #   restart: unless-stopped
  #   volumes:
  #     - user_mongo_data:/data/db
  #   networks:
  #     - training-network

  # training-mongo:
  #   image: mongo:7
  #   container_name: training-mongo
  #   restart: unless-stopped
  #   volumes:
  #     - training_mongo_data:/data/db
  #   networks:
  #     - training-network

  # attendance-mongo:
  #   image: mongo:7
  #   container_name: attendance-mongo
  #   restart: unless-stopped
  #   volumes:
  #     - attendance_mongo_data:/data/db
  #   networks:
  #     - training-network

  # ------------------ MICROSERVICES ------------------

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: unless-stopped
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo
    ports:
      - "4001:4001"
    networks:
      - training-network

  user-service:
    build: ./user-service
    container_name: user-service
    restart: unless-stopped
    env_file:
      - ./user-service/.env
    depends_on:
      - mongo
      - auth-service
    ports:
      - "4002:4002"
    networks:
      - training-network

  training-service:
    build: ./training-service
    container_name: training-service
    restart: unless-stopped
    env_file:
      - ./training-service/.env
    depends_on:
      - mongo
      - user-service
    ports:
      - "4003:4003"
    networks:
      - training-network

  attendance-service:
    build: ./attendance-service
    container_name: attendance-service
    restart: unless-stopped
    env_file:
      - ./attendance-service/.env
    depends_on:
      - mongo
      - user-service
      - training-service
    ports:
      - "4004:4004"
    networks:
      - training-network

  # ------------------ FRONTEND ------------------

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - auth-service
      - user-service
      - training-service
      - attendance-service
    ports:
      - "3000:80"
    networks:
      - training-network

# ------------------ NETWORK ------------------

networks:
  training-network:
    driver: bridge

# ------------------ VOLUMES ------------------

volumes:
  auth_mongo_data:
  user_mongo_data:
  training_mongo_data:
  attendance_mongo_data: